# This is a basic workflow to help you get started with Actions

name: CI

on:
  schedule:
      # every 6 hours
    - cron: "0 */6 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  generate:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 10

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:    
      - uses: Platane/snk@master
        with:
          github_user_name: aemc
          svg_out_path: github-contribution-grid-snake.svg
