name: generate animation

on:
  push:
    branches:
    - main 
  pull_request:
    branches: 
    - main 
  schedule:
      # every 6 hours
    - cron: "0 */6 * * *"

jobs:
  generate_animation:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: aemc
          gif_out_path: github-contribution-grid-snake.gif
          svg_out_path: github-contribution-grid-snake.svg

